name: noise_algorithms
description: Speed-improved perlin and simplex noise algorithms for 2D.
version: 0.1.0
author: Markus Ritberger
homepage: https://github.com/Slemgrim/noise_algorithms
dependencies: